### ISSUE TITLE
Pin repo in BIASlab org

### ISSUE THREAD

**Issue by bartvanerp** [biaslab/RxInfer.jl#76]
Perhaps let's pin this repository in the BIASlab organization to get it featured on the home page. Currently the ReactivePendulum is pinned there, but I think it also deserves a spot for `RxInfer` and others. Not sure who has permission to do so.

**Comment by bertdv** [comment]
done

**Comment by bartvanerp** [comment]
@bertdv I only see the reactivependulum and rocket. Rxinfer is still missing

**Comment by bvdmitri** [comment]
@bertdv I cannot see RxInfer in the pinned repositories either.
<img width="1712" alt="image" src="https://github.com/biaslab/RxInfer.jl/assets/6557701/a6ec668e-8330-4fb4-83f2-e9ee5249d002">

**Comment by bvdmitri** [comment]
@bertdv 
This task has been added to the [milestone](https://github.com/biaslab/RxInfer.jl/milestone/3) for tracking and prioritization.
